############################
# Label node
# kubectl get nodes
# kubectl label <node-name>  node-1 env=dev
#############################

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - dev
            - staging

  containers:
    - name: nginx
      image: nginx
      