apiVersion: v1
kind: Pod
metadata:
  name: init-demo

spec:
  initContainers:
    - name: init-check
      image: busybox
      command: ["sh", "-c", "echo initializing"]

  containers:
    - name: app
      image: nginx

  restartPolicy: Always