apiVersion: v1
kind: Pod
metadata:
  name: multiContainer-pod
spec:
  containers:
    - name: app
      image: nginx

    - name: log-agent
      image: busybox
      command: ["sh", "-c", "while true; do echo logging; sleep 5;"]