apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod

spec:
  containers:
    - name: app
      image: nginx

  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"