apiVersion: v1
kind: ResourceQuota

metadata:
  name: ecommerce-quota
  namespace: ecommerce

spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 5Gi
    pods: "20"