apiVersion: v1
kind: Secret
metadata:
  name: app-secret

# automatically convert value in base64
stringData:
  DB_USERNAME: "hatim"

  DB_HOST: "mysql"
  
  DB_PASSWORD: "123456"

  API_KEY: "123456dfg&*(DFGHJK"