apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job

spec:
  backoffLimit: 4

  completions: 5
  parallelism: 2
  
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["echo", "hello world"]

      restartPolicy: Never