apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev

spec:
  containers:
    - name: nginx
      image: nginx

      ports:
      - containerPort: 80

      resources:
        requests:
          cpu: "2"
          memory: "4Gi"

        limits: 
          cpu: "5"
          memory: "10Gi"


# Error from server (Forbidden): error when creating "ResourceQuota/exceeding-limit-pod.yml": pods "nginx-pod" is forbidden: [maximum cpu usage per Container is 1, but limit is 5, maximum memory usage per Container is 1Gi, but limit is 10Gi]