##############################################
# Don’t place 2 database Pods on same node
##############################################s

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app

    spec:
      containers:
        - name: app
          image: nginx


      affinity:
        podAntiAffinity: # DB is available in node nginx pod will not runs
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: db
              
              topologyKey: "kubernetes.io/hostname"