apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc

spec:
  storageClassName: fast-storage

  accessMode:
    - ReadWriteOnce

  resources:
    request:
      storage: 1Gi