apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulsets

spec:
  serviceName: mysql

  replicas: 3

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin@123"

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage

    spec:
      accessModes:
      - ReadWriteOnce


      resources:
        requests:
          storage: 5Gi