apiVersion: batch/v1
kind: Job

metadata:
  name: database-init
  namespace: ecommerce

spec:

  template:

    spec:

      restartPolicy: Never

      containers:

      - name: init-db

        image: postgres:15

        envFrom:

        - secretRef:
            name: app-secret

        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD

        command:

        - sh

        - -c

        - |
          until pg_isready \
            -h postgres-service \
            -U "$DB_USER" \
            -d "$DB_NAME"; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

          psql \
          -h postgres-service \
          -U "$DB_USER" \
          -d "$DB_NAME" \
          -f /scripts/init.sql

        volumeMounts:

        - name: sql-script
          mountPath: /scripts

      volumes:

      - name: sql-script

        configMap:

          name: db-init-script