apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv

spec:
  capacity:
    storage: 100Gi
  
  accessMode:
    - ReadWriteOnce

  storageClassName: ""

  mountOption:
    - region: us-east-1
  
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-pv
    volumeAttributes:
      backetName: my-s3-bucket